name: ANTMAN
channels:
  - https://repo.anaconda.com/pkgs/free/
  - https://repo.anaconda.com/pkgs/main
dependencies:
  - asn1crypto=0.22.0=py36_0
  - blas=1.0=mkl
  - certifi=2016.2.28=py36_0
  - cffi=1.10.0=py36_0
  - colorama=0.3.9=py36_0
  - cryptography=1.8.1=py36_0
  - idna=2.6=py36_0
  - mkl=2017.0.3=0
  - numpy=1.13.1=py36_0
  - openssl=1.0.2l=vc14_0
  - packaging=16.8=py36_0
  - pandas=0.20.3=py36_0
  - paramiko=2.1.2=py36_0
  - pip=9.0.1=py36_1
  - py=1.4.34=py36_0
  - pyasn1=0.2.3=py36_0
  - pycparser=2.18=py36_0
  - pyparsing=2.2.0=py36_0
  - pytest=3.2.1=py36_0
  - python=3.6.2=0
  - python-dateutil=2.6.1=py36_0
  - pytz=2017.2=py36_0
  - requests=2.14.2=py36_0
  - scikit-learn=0.19.0=np113py36_0
  - scipy=0.19.1=np113py36_0
  - setuptools=36.4.0=py36_1
  - six=1.10.0=py36_0
  - vc=14=0
  - vs2015_runtime=14.0.25420=0
  - wheel=0.29.0=py36_0
  - wincertstore=0.2=py36_0
